#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("xamarin_lim_kopi.Resource", IsApplication=true)]

namespace xamarin_lim_kopi
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int btnAlia = 2131034119;
			
			// aapt resource value: 0x7f050010
			public const int btnGau = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int btnGauPoDefault = 2131034127;
			
			// aapt resource value: 0x7f050008
			public const int btnLemon = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int btnMasala = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int btnMilkDefault = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int btnMilkO = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int btnMilkSee = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int btnPo = 2131034129;
			
			// aapt resource value: 0x7f050006
			public const int btnRandomDefault = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int btnSugarDefault = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int btnSugarLess = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int btnSugarMore = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int btnSugarZero = 2131034123;
			
			// aapt resource value: 0x7f050014
			public const int buttonOrder = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int editServings = 2131034131;
			
			// aapt resource value: 0x7f05000e
			public const int gridGauPo = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int gridMilk = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int gridSugar = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int toggleKopiTeh = 2131034112;
			
			// aapt resource value: 0x7f050012
			public const int togglePeng = 2131034130;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int Alia = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int Default = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int GarDai = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int Gau = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int Kopi = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int Kosong = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int Lemon = 2130968583;
			
			// aapt resource value: 0x7f04000e
			public const int MaiPeng = 2130968590;
			
			// aapt resource value: 0x7f040008
			public const int Masala = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int O = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int Order = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int Peng = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int Po = 2130968589;
			
			// aapt resource value: 0x7f040005
			public const int See = 2130968581;
			
			// aapt resource value: 0x7f040010
			public const int Servings = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public const int SiuDai = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int Teh = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
